name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup .NET 7 SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 7.0.100

      - name: Install Tools
        run: dotnet tool restore

      - name: Build
        run: dotnet run PublishDocs

      - name: Publish App
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: publish/app

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download app artifact
        uses: actions/download-artifact@v2.0.5
        with:
          name: app
          path: app
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: app
          CLEAN: true